INSERT INTO `universities` (`id`,`name`) VALUES
 (1,'Dr. B.A.T.'),
 (2,'Dr. B. A. Marathwada'),
 (3,'Mumbai'),
 (4,'North Maharashtra'),
 (5,'Pune'),
 (6,'Rashtrasant TukadojiMaharaj Nagpur'),
 (7,'S. R. T. Marathwada'),
 (8,'Sant Gadge BabaAmravati'),
 (9,'Shivaji'),
 (10,'S.N.D.T.'),
 (11,'Solapur');

insert into courses (id, code, name) values
(74,1,"Automobile Engineering"),
(75,6,"Bio-Medical Engineering"),
(62,8,"Chemical Engineering"),
(63,10,"Civil Engineering"),
(64,11,"Computer Engineering"),
(79,12,"Computer Science and Engg"),
(117,13,"Computer Technology"),
(65,16,"Electrical Engineering"),
(91,17,"Electrical Engg [Electrical and Power]"),
(107,18,"Environmental Engineering"),
(72,19,"Electronics Engineering"),
(70,20,"Electronics and Communication Engg"),
(119,21,"Electronics Product Design Technology"),
(113,22,"Electrical Engg [Electronics and Power]"),
(66,23,"Electronics and Tele-Comm Engg"),
(87,24,"Food Technology"),
(120,26,"Industrial Engineering"),
(93,27,"Industrial Electronics Engineering"),
(67,28,"Information Technology"),
(78,29,"Instrumentation Engineering"),
(68,30,"Mechanical Engineering"),
(82,31,"Mechanical Engineering [sandwich]"),
(118,33,"Mining Engineering"),
(102,34,"Man-Made Textile Technology"),
(108,35,"Oil and Paints Technology"),
(88,36,"Oil Fats and Waxes Technology"),
(114,37,"Oil Technology"),
(109,38,"Paper and Pulp Technology"),
(69,39,"Petro-Chemical Engineering"),
(110,40,"Petro-Chemical Technology"),
(89,41,"Paints Technology"),
(84,42,"Petroleum Engineering"),
(92,44,"Pharmaceutical and Fine Chemicals"),
(90,45,"Plastic Technology"),
(115,46,"Plastic and Polymer Technology"),
(111,48,"Polymer Technology"),
(85,49,"Polymer Engineering"),
(86,51,"Printing Engg and Graphics Comm"),
(73,52,"Production Engineering"),
(83,53,"Production Engineering [Sandwich]"),
(116,56,"Surface Coating Technology"),
(112,57,"Textile Engineering/Technology"),
(103,58,"Textile Chemistry"),
(104,59,"Textile Plant Engineering"),
(121,61,"Power Engineering"),
(105,62,"Textile Technology"),
(77,63,"Bio-Technology"),
(94,64,"B. Tech Computer Science and Engg"),
(95,65,"B. Tech Civil Engineering"),
(96,66,"B. Tech Mechanical Engineering"),
(97,67,"B. Tech Production Engineering"),
(98,68,"B. Tech Agricultural Engineering"),
(99,69,"B. Tech Electronics and Tele-CommEngg"),
(100,70,"B. Tech Instrumentation and ControlEngg"),
(101,71,"B. Tech Plastic and Polymer Engineering"),
(71,72,"Computer Science and Technology"),
(106,75,"Textile Engineering (Fashion Technology)"),
(81,76,"Instrumentation and Control"),
(80,98,"Printing and Packaging Technology");

INSERT INTO institutes (code, name, address, city, university) VALUES
("EN001","Dr.Babasaheb Ambedkar Technological","Lonere","","Dr. B.A.T."),
("EN101","SNDT Women's","Mumbai","Mumbai","SNDT"),
("EN202","Sardar Patel College of Engineering","Andheri","Mumbai","Mumbai"),
("EN204","Fr. Conceicao Rodrigues College of Engineering","Bandra","Mumbai","Mumbai"),
("EN205","K.J.Somaiya College of Engineering","Vidyavihar","Mumbai","Mumbai"),
("EN206","Anjuman-I-Islam's M.H. Saboo Siddik College of Engineering","Buyculla","Mumbai","Mumbai"),
("EN207","Padmabhushan Vasantdada Patil Pratishthans Collage of Enginnering","Sion","Mumbai","Mumbai"),
("EN209","Mahavir Education Trust's Shah & Anchor Kutchhi Engineering College","Chembur","Mumbai","Mumbai"),
("EN211","Thadomal Shahani Engineering College","Bandra","Mumbai","Mumbai"),
("EN212","Vivekanand Education Society's Institute of Technology","Chembur","Mumbai","Mumbai"),
("EN213","Konkan Gyanpeeth College of Engineering","","Karjat","Mumbai"),
("EN215","Mandar Education Society's Rajaram Shinde College of Engineering","Pedhambe","","Mumbai"),
("EN216","Finolex Academy of Management and Technology","","Ratnagiri","Mumbai"),
("EN217","Shivajirao S. Jondhale College of Engineering","Dombivali","Mumbai","Mumbai"),
("EN218","Agnel Charities' FR. C. Rodrigues Institute of Technology","Vashi","Navi Mumbai","Mumbai"),
("EN219","Jawahar Eduction Society's A. C. Patil College of Engineering","Kharghar","Navi Mumbai","Mumbai"),
("EN220","Bharati Vidyapeeth College of Engineering","Belapur, Kharghar","Navi Mumbai","Mumbai"),
("EN221","Lokmanya Tilak College of Engineering","Kopar Khairane","Navi Mumbai","Mumbai"),
("EN222","Manjara Charitable Trust's Rajiv Gandhi Institute of Technology","Andheri (W)","Mumbai","Mumbai"),
("EN223","M.G.M.'s College of Engineering and Technology","Kamothe","Navi Mumbai","Mumbai"),
("EN224","N.Y.S.S.'s Datta Meghe College of Engineering","Airoli","Navi Mumbai","Mumbai"),
("EN225","Ramrao Adik Education Society's Ramrao Adik Institute of Technology","Nerul","Navi Mumbai","Mumbai"),
("EN226","Smt. Indira Gandhi College of Engineering","Kopar Khoirane","Navi Mumbai","Mumbai"),
("EN227","Terna Engineering College","Nerul","Navi Mumbai","Mumbai"),
("EN228","Parshvanath College of Engineering","Kasarvadavali, Ghod Bunder Rd, Thane(W)","Mumbai","Mumbai"),
("EN229","Vidyavardhini's College of Engineering and Technology","Vasai, Thane","Mumbai","Mumbai"),
("EN230","Rizvi Education Society's Rizvi College of Engineering","Bandra","Mumbai","Mumbai"),
("EN231","Rajendra Mane College of Engineering & Technology","Ambav Deorukh","","Mumbai"),
("EN232","S.S.P.M.'s College of Engineering","Kankavli","","Mumbai"),
("EN233","Atharva College of Engineering","Malad(West)","Mumbai","Mumbai"),
("EN234","St. Francis Institute of Technology (Engineering College)","Borivali","Mumbai","Mumbai"),
("EN235","Vidyalankar Institute of Technology","Wadala","Mumbai","Mumbai"),
("EN236","M.E.S Pillai's Inst. of Information Technology, Media Studies and Research","New Panvel","","Mumbai"),
("EN237","Thakur College of Engineering and Technology","Kandivali","Mumbai","Mumbai"),
("EN238","Don Bosco Institute of Technology","","Mumbai","Mumbai"),
("EN239","K J Somaiya Institute Of Engineering And Information Technology","Sion","Mumbai","Mumbai"),
("EN240","Excelsior Education Society's K.C. College of Engineering","Thane(E)","","Mumbai"),
("EN241","S.I.E.S. Graduate School of Technology","Nerul","Navi Mumbai","Mumbai"),
("EN242","Watumull Institute of Electronics Engineering and Computer Technology","Worli","Mumbai","Mumbai"),
("EN243","Saraswati Education Soc's Saraswati College of Engineering","Kharghar","Navi Mumbai","Mumbai"),
("EN244","Yadavrao Tasgaonkar Institute of Technology","Chadhai, Bhiv-puri Road station, Tal Karjat","","Mumbai"),
("EN245","Xavier Institute Of Engineering C/O Xavier Technical Institute","Mahim","Mumbai","Mumbai"),
("EN246","Sardar Patel Institute of Technology","Andheri","Mumbai","Mumbai"),
("EN247","Gharda Foundation's Gharda Institute of Technology","Khed","Ratnagiri","Mumbai"),
("EN248","Vighnaharata Trust's Shivajirao S. Jondhale College of Engineering & Technology","Shahapur,Thane","","Mumbai"),
("EN249","Aldel Education Trust's St. John College of Engineering & Technology","Vevoor,Palghar","","Mumbai"),
("EN250","Koti Vidya Charitable Trust's Smt. Alamuri Ratnamala Institute of Engineering and Technology","Sapgaon, Tal. Shahapur","","Mumbai"),
("EN251","Saraswati Education Society, Yadavrao Tasgaonkar College of Engineering and Management","Chandai","Karjat","Mumbai"),
("EN302","Padmashri Dr. Vithalrao Vikhe Patil College of Engineering","Ahmednagar","","Pune"),
("EN303","Sanjivani Rural Education Society's College of Engineering","Kopargaon","","Pune"),
("EN304","Pravara Rural Engineering College","Loni","","Pune"),
("EN305","Amrutvahini Sheti & Shikshan Vikas Sanstha's Amrutvahini College of Engineering","Sangamner","","Pune"),
("EN306","KKWES's K.K. Wagh Institute of Engineering Education & Research","", "Nashik","Pune"),
("EN307","Shivnagar Vidya Prasarak Mandal's College of Engineering","Malegaon-Baramati","","Pune"),
("EN308","All India Shri Shivaji Memorial Society's College of Engineering","Pune","","Pune"),
("EN309","MKSSS's Cummins College of Engineering for Women","","Pune","Pune"),
("EN310","Dr. D.Y.Patil Pratishthan's D.Y.Patil College of Engineering","Akurdi","Pune","Pune"),
("EN311","Maharashtra Institute of Technology","Kothrud","Pune","Pune"),
("EN312","Pune Institute of Computer Technology","Dhankavdi","Pune","Pune"),
("EN313","Pune Vidyarthi Griha's College of Engineering and Technology","Pune","","Pune"),
("EN314","Sinhgad College of Engineering","Vadgaon (BK)","Pune","Pune"),
("EN316","Padmashri Dr.D.Y. Patil Institute of Engineering and Technology","Pimpri","Pune","Pune"),
("EN317","Pravara Rural Education Society's Sir Visvesvaraya Memorial Engineering College","Chincholi","Nashik","Pune"),
("EN318","P.D.E.A.'s Lata Annasaheb Gopalrao Awate College of Engineering","Hadapsar","Pune","Pune"),
("EN319","Nashik District Maratha Vidya Prasarak Samaj's College of Engineering","Nashik","","Pune"),
("EN320","All India Shri Shivaji Memorial Society,s Institute of Information Technology","", "Pune","Pune"),
("EN321","Maharashtra Academy of Engineering","Alandi","Pune","Pune"),
("EN322","Progressive Education Society's Modern College of Engineering","","Pune","Pune"),
("EN323","Modern Education Society's College of Engineering","Pune","","Pune"),
("EN324","Genba Sopanrao Moze Trust's Genba Sopanrao Moze College of Engineering","Pune","","Pune"),
("EN325","Pimpri Chinchwad College of Engineering","Nigdi","Pune","Pune"),
("EN326","Vidya Pratishathan's College of Engineering","Baramati","Pune","Pune"),
("EN327","STES Smt. Kashibai Navale College of Engineering","Vadgaon","Pune","Pune"),
("EN328","MAEER's M.I.T. College of Engineering","Kothrud","Pune","Pune"),
("EN329","Rajarshi Shahu College of Engineering","Tathawade","Pune","Pune"),
("EN330","Bharati Vidyapeeth's College of Engineering for Women","Katraj, Dhankawadi","Pune","Pune"),
("EN331","B.R.A.C.T's Vishwakarma Institute of Information Technology","Kondhwa (Bk.)","Pune","Pune"),
("EN332","JSPM's Jayawantrao Sawant college of Engineering","","Pune","Pune"),
("EN333","SNJB's College of Engineering, (Jain Gurukul)","Neminagar,Chandwad","Nashik","Pune"),
("EN334","Sinhagad Institute of Technology","","Lonavala","Pune"),
("EN335","Sinhgad Academy Of Engineering","Kondhwa(Bk.), Kondhwa-Saswad Road","Pune","Pune"),
("EN336","Choudhari Attarsingh Yadav Memorial Trust's Siddhant College Of Engineering","Sundumbare","","Pune"),
("EN337","Imperial College of Engineering & Research","Wagholi","Pune","Pune"),
("EN338","SSMS's Padmabnooshan Vasantdada Patil Institute of Technology","","Pune","Pune"),
("EN339","Genba Sopanrao Moze Trust's Parvatibai Genba Moze College of Engineering","Wagholi","Pune","Pune"),
("EN340","MET's Institute of Engineering, Bhujbal Knowledge City, MET League of Colleges","Adgaon","Nashik","Pune"),
("EN341","Jagdamba Education Soc.Nashik's S.N.D. College of Engineering & Research","Babulgaon","","Pune"),
("EN342","Marathwada Mitra Mandal's College of Engineering","Pune","","Pune"),
("EN343","G.H. Raisoni College of Engineering & Management","Wagholi, Nagar Road","Pune","Pune"),
("EN344","Indira College of Engineering & Management","Pune","","Pune"),
("EN345","Zeal Education Society's Dyanganga College of Engineering & Research","Haveli","Pune","Pune"),
("EN346","G H Raisoni Institute of Engineering and Technology","Wagholi","Pune","Pune"),
("EN347","Marathwada Mitra Mandal's Institute of Technology","Lohagaon","","Pune"),
("EN348","Vishwabharati Academy's College of Engineering","","Ahmednagar","Pune"),
("EN349","Sandip Foundation, Sandip Institute of Technology and Research Centre","Mahiravani","Nashik","Pune"),
("EN350","Ignited Minds Society, Mulshi Institute of Technology and Research","Sambhave,Mulshi","","Pune"),
("EN351","Matoshri College of Engineering and Research Centre","Eklahare","Nashik","Pune"),
("EN352","Al-Ameen Educational and Medical Foundation, College of Engineering","Koregaon","Bhima","Pune"),
("EN353","K.J.'s Educational Institute Trinity College of Engineering and Research","Pisoli,Haveli Dist","Pune","Pune"),
("EN354","Dhole Patil Education Society, Dhole Patil College of Engineering","Wagholi", "Taluka Haveli","Pune"),
("EN356","Nutan Maharashtra Vidya Prasarak Mandal, Nutan Maharashtra Institute of Technology","Vishnupuri, Maval","","Pune"),
("EN357","Nashik Gramin Shikshan Prasarak Mandal's Brahma Valley College of Engineering and Research Institute","Anjaneri","Nashik","Pune"),
("EN358","S.G.R. Education Foundation, College of Engineering and Management","Ahmednagar","","Pune"),
("EN359","Sinhgad Technical Education Society, Sinhgad Institute of Technology and Science","Nahre (Ambegaon)","","Pune"),
("EN401","Government College of Engineering","","Jalgaon","North Maharashtra"),
("EN402"," Department of Chemical Technology","","Jalgaon","North Maharashtra"),
("EN403","S.S.V.P.S.'s Bapusaheb Shivajirao Deore College of Engineering","","Dhule","North Maharashtra"),
("EN404","Nagaon Education Society's Gangamai College of Engineering","Nagaon, Tal DistDhule","","North Maharashtra"),
("EN405","Sanjay Education Society's College of Engineering","Navalnagar","","North Maharashtra"),
("EN406","P.S.G.V.P. Mandal's D.N. Patel College of Engineering","Shahada, Dist. Nandurbar","","North Maharashtra"),
("EN407","T.M.E. Society's J.T.Mahajan College of Engineering","Faizpur","","North Maharashtra"),
("EN408","S.S.B.T.'s College of Engineering and Technology","","Jalgaon","North Maharashtra"),
("EN409","Hindi Seva Mandal's Shri Sant Gadgebaba College of Engineering & Technology","Bhusawal","","North Maharashtra"),
("EN410","Godavari Foundation's Godavari College Of Engineering","","Jalgaon","North Maharashtra"),
("EN411","Shrikrishna Educational & Cultural Mandal's Shri Sureshdada Jain College of Engineering","","Jalgaon","North Maharashtra"),
("EN412","K.C.E. Society's College of Engineering and Information Technology","","Jalgaon","North Maharashtra"),
("EN413","R. C. Patel Institute of Technology","","Shirpur","North Maharashtra"),
("EN414","GHR.Educational Foundation Society, G.H.Raisoni Institute of Engineering & Mangement","","Jalgaon","North Maharashtra"),
("EN501","Government College of Engineering","","Aurangabad","Dr. B. A. Marathwada"),
("EN502"," Department of Chemical Technology","","Aurangabad","Dr. B. A. Marathwada"),
("EN503","M.G.M.'s Jawaharlal Nehru Engineering College","","Aurangabad","Dr. B. A. Marathwada"),
("EN504","Gramodik Shikshan Mandal's Marathwada Institute of Technology","","Aurangabad","Dr. B. A. Marathwada"),
("EN505","Peoples Education Society's College of Engineering","","Aurangabad","Dr. B. A. Marathwada"),
("EN506","Mahatma Basaweshwar Education Society's College of Engineering","Ambejogai","","Dr. B. A. Marathwada"),
("EN507","Terna Public Charitable Trust's College of Engineering","","Osmanabad","Dr. B. A. Marathwada"),
("EN508","Shree Tuljabhavani College of Engineering","","Tuljapur","Dr. B. A. Marathwada"),
("EN509","Hi-Tech Institute of Technology","","Aurangabad","Dr. B. A. Marathwada"),
("EN510","Aditya Engineering College","","Beed","Dr. B. A. Marathwada"),
("EN511","Nagnathappa Halge Engineering College","Parli","","Dr. B. A. Marathwada"),
("EN512","G. S. Mandals Mahrashtra Institute of Technology","","Aurangabad","Dr. B. A. Marathwada"),
("EN513","Matsyodari Shikshan Sansatha's College of Engineering and Technology","","Jalna","Dr. B. A. Marathwada"),
("EN514","Lokvikas Educational & Charitable Trust, Savitribai Phule Women's Engineering College","","Sharnapur","Dr. B. A. Marathwada"),
("EN515","Shree Yash Pratishthan, Shreeyash College of Engineering and Technology","Satara(P), Dist. Aurangabad","","Dr. B. A. Marathwada"),
("EN602","M.S. Bidve Engineering College","","Latur","S. R. T. Marathwada"),
("EN603","Maharashtra College of Engineering","","Nilanga","S. R. T. Marathwada"),
("EN605","M.G.M's College of Engineering","","Nanded","S. R. T. Marathwada"),
("EN701","Government College of Engineering","","Karad","Shivaji"),
("EN703","Dattjirao Kadam Technical Education Society's Textile & Engineering Institute","","Ichalkaranji","Shivaji"),
("EN704","Dr. J.J. Magdum Charitable Trust's Dr. J.J. Magdum College of Engineering","Jaysingpur","","Shivaji"),
("EN705","D.Y. Patil College of Engineering and Technology","","Kolhapur","Shivaji"),
("EN706","Kolhapur Institute of Technology College of Engineering","","Kolhapur","Shivaji"),
("EN707","Tatyasaheb Kore Institute of Engineering and Technology","","Warananagar","Shivaji"),
("EN708","Shetkari Shikshan Mandal's Pad. Vasnatraodada Patil Institute of Technology","Budhgaon","Sangli","Shivaji"),
("EN709","Kasegaon Education Society's Rajarambapu Institute of Technology","","Rajaramnagar","Shivaji"),
("EN710","Karmaveer Bhaurao Patil College of Engineering and Polytechnic","", "Satara","Shivaji"),
("EN711","Walchand Institute of Technology","","Solapur","Shivaji"),
("EN712","Shri Vithal Education and Research Institute's College of Engineering","","Pandharpur","Solapur"),
("EN713","Annasaheb Dange College of Engineering and Technology","Ashta","Sangli","Shivaji"),
("EN714","Bharati Vidyapeeth's College of Engineering","","Kolhapur","Shivaji"),
("EN715","KSGBS's Bharat- Ratna Indira Gandhi College of Engineering","Kegaon","Solapur","Solapur"),
("EN716","Kai Amdar Brahmdevdada Mane Shikshan va Samajik Prathistan's Brahmdevdada Mane Institute of Technology","","Solapur","Solapur"),
("EN717","Gaurishankar Educational & Charitable Trust's Satara College of Engineering & Management","Limb","Satara","Shivaji"),
("EN718","Late Narayandas Bhawandas Chhabad Institute of Engineering & Technology","","Satara","Shivaji"),
("EN719","Shanti Education Society, A.G. Patil Institute of Technology","Soregaon","Solapur(North)","Solapur "),
("EN720","Pradnya Niketan Education Society, The Orchid College of Engineering and Technology","","Solapur(South)","Solapur "),
("EN721","Loknete Hanumantrao Charitable Trust's Adarsh Institute of Technology and Research","Khambale Tal. Khanapur","","Shivaji"),
("EN722","G.K. Gujar Memorial Charitable Trust, Dr. Daulatrao Aher College of Engineering","","Karad","Shivaji"),
("EN801","Government College of Engineering","","Amravati","Sant Gadge BabaAmravati"),
("EN802"," Department of Chemical Technology","Amravati","Amravati","Sant Gadge BabaAmravati"),
("EN803","Shri Shivaji Education Society's College of Engineering and Technology","","Akola","Sant Gadge BabaAmravati"),
("EN804","V.Y.W.S's Prof. Ram Meghe Institute of Technology & Research (Formerly College of Engineering)","Badnera","Amravati","Sant Gadge BabaAmravati"),
("EN805","Paramahans Ramkrishna Maunibaba Shikshan Santha's , Anuradha Engineering College","Chikhali","","Sant Gadge BabaAmravati"),
("EN806","Shri Sant Gajanan Maharaj College of Engineering","","Shegaon","Sant Gadge BabaAmravati"),
("EN807","Janata Shikshan Prasarak Mandal’s Babasaheb Naik College Of Engineering","Pusad","","Sant Gadge BabaAmravati"),
("EN808","Jawaharlal Darda Institute of Engineering and Technology","Yavatmal","","Sant Gadge BabaAmravati"),
("EN809","Sipna Shikshan Prasarak Mandals College of Engineering & Technology","","Amravati","Sant Gadge BabaAmravati"),
("EN810","Shri Hanuman Vyayam Prasarak Mandals College of Engineering & Technology","","Amravati","Sant Gadge BabaAmravati"),
("EN811","Dr. Bhausaheb Nadurkar College of Engineering","Waghapur","Yavatmal","Sant Gadge BabaAmravati"),
("EN812","Shri. Dadasaheb Gawai Charitable Trust's Dr. Smt. Kamlatai Gawai Institute of Engineering & Technology","","Darapur","Sant Gadge BabaAmravati"),
("EN813","Dwarka Bahu Uddeshiya Gramin Vikas Foundation, Rajarshri Shahu College of Engineering","","Buldhana","Sant Gadge BabaAmravati"),
("EN814","Maratha Shikshan Sanstha, P.R. Patil College of Engineering","","Amravati","Sant Gadge BabaAmravati"),
("EN815","Chaitanya Bahu Uddeshiya Sanstha, College of Engineering and Management","Anjangaon","Amravati","Sant Gadge BabaAmravati"),
("EN816","Indira Bahuuddeshiya Shikshan Sanstha, College of Engineering","Ghatkheda","Amravati","Sant Gadge BabaAmravati"),
("EN901","Government College of Engineering","","Chandrapur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN902","Laxminarayan Institute of Technology","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN904","Gondia Education Society's Manoharbhai Patel Institute of Engineering and Technology","","Gondia","Rashtrasant TukadojiMaharaj Nagpur"),
("EN905","Rajiv Gandhi College of Engineering Research & Technology","","Chandrapur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN906","Ankush Shikshan Sanstha's G.H Raisoni College of Engineering","Digdoh","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN907","Karmavir Dadasaheb Kannamwar College of Engineering","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN908","Priyadarshani College of Engineering","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN909","Shri. Ramdeo Baba Kamla Nehru Engineering College","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN910","Yeshwantrao Chavan College of Engineering","Wanadongri","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN911","Vodithala Education Society's Kavikulguru Institute of Technology and Science(KITS)","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN912","Bapurao Deshmukh College of Engineering","Sevagram Dist. Wardha","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN913","Sanmarg Shikshan Sanstha's Smt. Radhikatai Pandav College of Engineering","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN914","B.C.Y.R.C`s Umrer College of Engineering","Umrer","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN915","Lokmanya Tilak Jankalyan Shikshan Sanstha's , Priyadarshini Institute of Engineering and Technology","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN916","Anjuman College of Engineering & Technology","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN917","National Power Training Institute (Under the Ministry of Power, Govt. of India)","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN918","ST. Vincent Pallotti College of Engineering & Technology","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN919","JMSS Shri Shankarprasad Agnihotri College of Engineering","Wardha","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN920","Guru Nanak Institute of Engineering & Technology","Kalmeshwar","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN921","Tulsiramji Gaikwad-Patil College of Engineering & Technology","Mohgaon","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN922","Shri Bhagwati Chaturvedi College of Engineering","Harpur Nagar","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN923","Amar Seva Mandals Shree Govindrao Vanjari College of Engineering & Technology","Salai Godhani","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN924","Lokmanya Tilak Jankalyan Shiksan Sanstha, Priyadarshini Indira Gandhi College of Engineering","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN925","Shree Vidyarthi Sudhar Sangha College of Engineering & Research","Wandongari","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN926","Jaidev Education Society, J. D. College of Engineering","Khandala, Post Valni, KatolRoad","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN927","Datta Meghe Institute of Medical Science's Datta Meghe Institute of Engg & Tech.& Research, Savangi (Meghe)","Wardha","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN928","Sir Shantilal Badjate Charitable Trust's S. B. Jain Institute of Technology,Managment & Research","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN929","Nagar Yuvak Shikshak Sanstha, N.Y.S.S. College of Engineering & Research","Wanadongari","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN930","Backward Class Youth Relief Committee, Shrimati Rajashri Mulak College of Engineering for Women","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN931","Samridhi Sarwajanik Charitable Trust, Jhulelal Institute of Technology","Lonara,Koradi Road, Dist. Nagpur","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN932","Sarvasiddhanta Education Soc's Nuva College of Engineering and Technology","", "Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN933","Lokmanya Tilak Jankalyan Shiksan Sanstha, J. L. Chaturvedi College ofEngineering, Nandanvan","","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN944","Shree Bapuraoji Deshmukh Foundation, Suresh Deshmukh College of Engineering","Selukate","Wardha","Rashtrasant TukadojiMaharaj Nagpur"),
("EN945","Dr. Brahmanand B. Karanjekar, Vainganga College of Engineering and Management","Dongargaon, Wardha Road","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN946","Om Arunodaya Bahuuddeshiya Khadi Garmudyog Vikas Sanstha's Om College of Engineering","Inzapur","Wardha","Rashtrasant TukadojiMaharaj Nagpur"),
("EN947","Shriram Gram Vikas Shikshan Sansta, Vilasrao Deshmukh College of Engineeringand Technology","Mauda, Dist. Nagpur","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN948","Bhausaheb Charitable Trust's Bhausaheb Mulik College of Engineering","Butibori","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN949","Sanmarg Shikshan Sanstha, Mandukarrao Pandav College of Engineering","Billewada, Bhandara","Nagpur","Rashtrasant TukadojiMaharaj Nagpur"),
("EN950","Shri. Sai Shikshan Sanstha, Nagpur Institute of Technology","Mahuzari","","Rashtrasant TukadojiMaharaj Nagpur"),
("EN951","Ankush Shikshan Sanstha's G.H.Raisoni Institute of Engineering & Technology for Women","", "Nagpur","Rashtrasant TukadojiMaharaj Nagpur");
