INSERT INTO `universities` (`id`,`name`) VALUES
 (1,'Dr. B.A.T.'),
 (2,'Dr. B. A. Marathwada'),
 (3,'Mumbai'),
 (4,'North Maharashtra'),
 (5,'Pune'),
 (6,'Rashtrasant Tukadoji Maharaj Nagpur'),
 (7,'S. R. T. Marathwada'),
 (8,'Sant Gadge Baba Amravati'),
 (9,'Shivaji'),
 (10,'S.N.D.T.'),
 (11,'Solapur');

insert into courses (id, course_code, name) values
(74,1,"Automobile Engineering"),
(75,6,"Bio-Medical Engineering"),
(62,8,"Chemical Engineering"),
(63,10,"Civil Engineering"),
(64,11,"Computer Engineering"),
(79,12,"Computer Science and Engg"),
(117,13,"Computer Technology"),
(65,16,"Electrical Engineering"),
(91,17,"Electrical Engg [Electrical and Power]"),
(107,18,"Environmental Engineering"),
(72,19,"Electronics Engineering"),
(70,20,"Electronics and Communication Engg"),
(119,21,"Electronics Product Design Technology"),
(113,22,"Electrical Engg [Electronics and Power]"),
(66,23,"Electronics and Tele-Comm Engg"),
(87,24,"Food Technology"),
(120,26,"Industrial Engineering"),
(93,27,"Industrial Electronics Engineering"),
(67,28,"Information Technology"),
(78,29,"Instrumentation Engineering"),
(68,30,"Mechanical Engineering"),
(82,31,"Mechanical Engineering [sandwich]"),
(118,33,"Mining Engineering"),
(102,34,"Man-Made Textile Technology"),
(108,35,"Oil and Paints Technology"),
(88,36,"Oil Fats and Waxes Technology"),
(114,37,"Oil Technology"),
(109,38,"Paper and Pulp Technology"),
(69,39,"Petro-Chemical Engineering"),
(110,40,"Petro-Chemical Technology"),
(89,41,"Paints Technology"),
(84,42,"Petroleum Engineering"),
(92,44,"Pharmaceutical and Fine Chemicals"),
(90,45,"Plastic Technology"),
(115,46,"Plastic and Polymer Technology"),
(111,48,"Polymer Technology"),
(85,49,"Polymer Engineering"),
(86,51,"Printing Engg and Graphics Comm"),
(73,52,"Production Engineering"),
(83,53,"Production Engineering [Sandwich]"),
(116,56,"Surface Coating Technology"),
(112,57,"Textile Engineering/Technology"),
(103,58,"Textile Chemistry"),
(104,59,"Textile Plant Engineering"),
(121,61,"Power Engineering"),
(105,62,"Textile Technology"),
(77,63,"Bio-Technology"),
(94,64,"B. Tech Computer Science and Engg"),
(95,65,"B. Tech Civil Engineering"),
(96,66,"B. Tech Mechanical Engineering"),
(97,67,"B. Tech Production Engineering"),
(98,68,"B. Tech Agricultural Engineering"),
(99,69,"B. Tech Electronics and Tele-CommEngg"),
(100,70,"B. Tech Instrumentation and ControlEngg"),
(101,71,"B. Tech Plastic and Polymer Engineering"),
(71,72,"Computer Science and Technology"),
(106,75,"Textile Engineering (Fashion Technology)"),
(81,76,"Instrumentation and Control"),
(80,98,"Printing and Packaging Technology");